const express = require('express');
const mongoose = require('mongoose');
var bodyParser = require('body-parser');
const nodemailer = require("nodemailer");
const cors = require('cors');
const multer = require("multer");
var storage = multer.memoryStorage();
var upload = multer({ storage: storage });
const Post = require('./schema/postSchema');
const connectDB = require("./config/db.config")();
const auth =  require('./middleware/auth')

const app = express();
mongoose.set('useNewUrlParser', true);
mongoose.set('useFindAndModify', false);
mongoose.set('useCreateIndex', true);
app.use(cors())
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.static(__dirname + '/public'));
app.use((req, res, next) => {
    res.setHeader('Access-Control-Allow-Origin', '*')
    res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE')
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization')
    next()
})

//routes

app.get('/', (req, res) => {
    console.log(req.body)
    console.log(req.params)

    return res.status(200).send({
        message: "All Ok"
    })
})

const { getFilteredInfo, getThemeoftheMonth, getMostDownloaded,setThemeOfTheMonth }= require('./handlers/info');
const { uploadFile,deleteFile,addDownloadCount } = require('./handlers/s3.CRUD')

app.post('/upload-file', [auth,upload.single('file')],uploadFile)
app.delete('/file/:key',[auth,upload.single('file')],deleteFile)
app.post('/download-file', addDownloadCount)
app.post('/getFilteredInfo', getFilteredInfo)
app.get('/most-downloaded', getMostDownloaded)
app.get('/getThemesOfTheMonth', getThemeoftheMonth)
app.post('/set-theme-of-the-month',auth,setThemeOfTheMonth)

const { getPostInfo, deletePost, updatePostInfo, addPost,script } = require('./handlers/Posts')

app.get('/posts/:postID', getPostInfo)
app.delete('/posts/:postID', auth, deletePost)
app.put('/posts/:postID', auth, updatePostInfo)
app.post('/post',auth,addPost)
app.get('/runScript',script)

const { addSortingData, getSortingData, modifySortingData, delFromSortingData } = require('./handlers/sortingDataRoutes')

app.post('/addSortingData',auth,addSortingData)
app.get('/getSortingData', getSortingData)
app.post('/modifySortingData', auth, modifySortingData)      //TODO: Add Auth  // ADD + EDIT things
app.post('/deleteFromSortingData', auth, delFromSortingData) //TODO: Add Auth  // REMOVE things


const { addAdmin, login , validAdmin} = require('./handlers/admin')

// app.post('/login', login)
// app.post('/isValidAdmin',Auth,validAdmin)
app.post('/s3-upload',upload.single("file"))
app.post('/contactUsFormSubmission', (req, res) => {
    // console.log(req.body)
    let data = req.body;
    // const { parse } = require('json2csv');
    // create reusable transporter object using the default SMTP transport
    var transporter = nodemailer.createTransport({
        host: 'smtp.gmail.com',
		port: 465,
		secure: true,
        service: 'gmail',
        auth: {
            user: 'poshangyan@gmail.com',
            pass: 'Anshaj@123'
        }
    });

    var message = {
        from: "sender@server.com",
        to: "anshajkumarsharma@gmail.com,poshangyan-niti@gov.in,meetridhi@2626.today",
        subject: "Message from Contact Form",
        html: `<p>Hello ,</p>
        <p>Received a message fom <strong>${data.name}.</strong></p>
        <p>Message: ${data.message}</p> 
        <p> PhoneNo: ${data.phoneNo}</p>
        <p> Email: ${data.email} </p>
        <p>It is autogenerated email feel free to contact in case of any issue.</p>
        <p>Thanks,</p>
        <p>Poshan Gyan Team</p>`,
    };

    transporter.sendMail(message, (error, info) => {
        if (error) {
            console.log(error);
            res.status(403).send({ err: "Error in sending email...." });
        } else {
            res.status(200).send({ message: "Email sucessfully sent.." });
        }
    });
})

const {createZip} = require('./utils/zipAndDownload')
const {downloadZip} = require('./utils/zipAndDownload')
const {checkZipFiles} = require('./utils/zipAndDownload')

app.get('/download-zip/:name',downloadZip)
app.post('/create-zip',createZip);
app.get('/fetch-all-zips',checkZipFiles)
app.get('/download', function(req, res){
    const file = `${__dirname}/ASD.json`;
    res.download(file); // Set disposition and send it.
});

var schedule = require('node-schedule');

// run every Friday at 6:00 PM
schedule.scheduleJob('07 19 * * 4', () => {
    const { parse } = require('json2csv');


    Post.find()
        .then(res => {
            // console.log(csv)
            // console.log(res)
            let data = [];
            res.forEach((doc) => {
                let temp = {
                    downloadsCount: doc.downloadsCount,
                    thumbBucket: doc.thumbBucket,
                    mimetype: doc.mimetype,
                    thumbLocation: doc.thumbLocation,
                    label: doc.label,
                    Bucket: doc.Bucket,
                    postId: doc.postId,
                    languages: doc.languages,
                    showFileName: doc.showFileName,
                    mediaType: doc.mediaType,
                    thumbKey: doc.thumbKey,
                    themes: doc.themes,
                    Location: doc.Location,
                    thumbkey: doc.thumbKey,
                    Key: doc.Key,
                    source: doc.source,
                    targetAudience: doc.targetAudience,
                }
                data.push(temp);
            });
            const csv = parse(data, ["source", "Bucket"]);
            var transporter = nodemailer.createTransport({
                service: 'gmail',
                auth: {
                    user: 'poshangyan@gmail.com',
                    pass: 'Anshaj@123'
                }
            });

            var message = {
                from: "sender@server.com",
                to: "anshajkumarsharma@gmail.com,poshangyan-niti@gov.in,meetridhi@2626.today,meetmanik@2626.today,meetkanika@2626.today,\
                diksha.radhakrishnan@ashoka.edu.in,sailee.adhao@ashoka.edu.in",
                subject: "Database Weekly Update",
                html: `Updated database`,
                attachments: [
                    {
                        filename: "updated_database.csv",
                        content: csv,
                    },
                ]
            };



            transporter.sendMail(message, (error, info) => {
                if (error) {
                    console.log(error);
                    console.log({ err: "Error in sending email...." });
                } else {
                    console.log({ message: "Email sucessfully sent.." });
                }
            });

        }).catch(e => {
            console.log(e)
        })
})
console.log(new Date().toString())
// schedule.scheduleJob('*/2 * * * 4', () => {
//     console.log(new Date().toString())
// })
schedule.scheduleJob('30 00 19 * * 4', () => {
    const { parse } = require('json2csv');
    console.log(new Date().toString())

    Post.find()
        .then(res => {
            // console.log(csv)
            // console.log(res)
            let data = [];
            res.forEach((doc) => {
                let temp = {
                    downloadsCount: doc.downloadsCount,
                    thumbBucket: doc.thumbBucket,
                    mimetype: doc.mimetype,
                    thumbLocation: doc.thumbLocation,
                    label: doc.label,
                    Bucket: doc.Bucket,
                    postId: doc.postId,
                    languages: doc.languages,
                    showFileName: doc.showFileName,
                    mediaType: doc.mediaType,
                    thumbKey: doc.thumbKey,
                    themes: doc.themes,
                    Location: doc.Location,
                    thumbkey: doc.thumbKey,
                    Key: doc.Key,
                    source: doc.source,
                    targetAudience: doc.targetAudience,
                }
                data.push(temp);
            });
            const csv = parse(data, ["source", "Bucket"]);
            var transporter = nodemailer.createTransport({
                service: 'gmail',
                auth: {
                    user: 'poshangyan@gmail.com',
                    pass: 'Anshaj@123'
                }
            });

            var message = {
                from: "sender@server.com",
                to: "anshajkumarsharma@gmail.com",
                subject: "Database Weekly Update dd",
                html: `Updated database`,
                attachments: [
                    {
                        filename: "updated_database.csv",
                        content: csv,
                    },
                ]
            };



            transporter.sendMail(message, (error, info) => {
                if (error) {
                    console.log(error);
                    console.log({ err: "Error in sending email...." });
                } else {
                    console.log({ message: "Email sucessfully sent.." });
                }
            });

        }).catch(e => {
            console.log({ err: "Error in sending email.... 2" });
        })
})

app.use("/2626/", require("./handlers/admin"));

app.use((error, req, res, next) => {
    console.log(error)
    const status = error.statusCode || 500
    const message = error.message
    const data = error.data
    res.status(status).json({
        message: message,
        data: data
    })
})


    const PORT = process.env.PORT || 3000;
    app.listen(PORT,()=>{
        console.log(`${process.env.NODE_ENV || "Production"} server is listening on PORT ${PORT}`)
    })

