const BUCKET_NAME = 'poshangyan';
const IAM_USER_KEY = 'AKIAIBPSAP26ORSB5DOA';
const IAM_USER_SECRET = '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';

module.exports = {BUCKET_NAME,IAM_USER_KEY,IAM_USER_SECRET}